### ISSUE TITLE
Is it possible to parse json with mixed lists?

### ISSUE THREAD

**Issue by NicoVIII** [vsapronov/FSharp.Json#11]
At first: Thanks for this library!
I'm working with it to parse JSON responses from an API and it really works like a charm. If I correctly create types for the expected response, I can work type-safe with that data.
But now the API sends inconsistent data, I get a list where complex objects and strings are mixed.

It looks like that:
`{
  "downloads": [
    [
        "English",
        {..}
    ]
  ]
}`

Is there some elegant way to handle such mixed lists with this library? I tried different approaches but none worked.

**Comment by vsapronov** [comment]
The one simplest option would be to try to deserialize as `object list` type. Unfortunately not really helpful as you will need to do types casting in F# code manually.
The other more helpful option would be: serialize/deserialize record type into list with members mapped positionally. Meaning that #0 element of the list always goes to particular member of the record type, #1 element goes to another member of the record type, etc. Mappings #0 #1 to record members could be done through attribute as names are mapped now. Is this what you would like to have? For this to work your lists should be always of the same structure. As you can imagine this is big work but not impossible, so let's agree on what you need first....

**Comment by vsapronov** [comment]
@NicoVIII ^

**Comment by NicoVIII** [comment]
Thank you for your fast response and sorry for my late one :grin: 

I guess, the list will always have the same structure so your second approach should be usable. I'm a bit confused though, is it a suggestion for me to implement in my program or a suggestion what could be added to the library itself?

The day I asked the question I played around and found out that I can use the "untyped" setting and use the generated Maps (together with some `match resp with | :? Map<string, obj>` "casts"). It is not very beautiful but works, so there is no need to hurry.

**Comment by NicoVIII** [comment]
Hi!
I'm very sorry that I didn't answer and am quite sure, that an answer now will not help you since over a year past...
But for the record I want to write an answer anyway!

I personally used Transforms to read out my information in a helpful way for me. You can have a look at that here:
https://github.com/NicoVIII/GogApi.DotNet/commit/7a89344ca8da7164d7f4f0190031fd9887957c99

I'm not very experienced in F# (I only use it in hobby projects) so I'm not sure if this is the best way. But I guess a similar approach could work to get a list like you requested there:

Write a Transform from DecodedValue list into a obj list and write transformation functions for both directions (or only the one you need, I used only one direction, because I'm only reading) and add it to the field with [<JsonField(Transform=typeof<...>)>].
To do that I cast it one by one to the assumed type. I'm not sure how to get the correct type here for the DecodedValue DU, but I guess you could use a type match
```
// Untested - call it Pseudocode
match something with
| :? string as value -> String value
| :? int as value -> Integer value
...
```
approach or maybe something like TryParse?

Maybe this helps when people in the future need something like that again in the future...

**Comment by sebastian** [comment]
Thank you @NicoVIII! I really appreciate your detailed answer and the links! A year or not, I still learnt lots reading this!
