### ISSUE TITLE
uints not supported

### ISSUE THREAD

**Issue by oauo** [vsapronov/FSharp.Json#16]
```
JsonDeserializationError: JSON Path: guild. Not supported type: UInt64
```

Do I need to say more?

**Comment by vsapronov** [comment]
I will add support for it soon. Stay tuned.

**Comment by vsapronov** [comment]
https://github.com/vsapronov/FSharp.Json/pull/21

**Comment by vsapronov** [comment]
Please try version 0.3.7 - support for various numeric types was added
