### ISSUE TITLE
Represent single-case unions as their wrapped type

### ISSUE THREAD

**Issue by cmeeren** [vsapronov/FSharp.Json#2]
Single-case DUs are frequently used for added type safety in F#. Since this is such a common pattern, any F# serialization library worth its salt should be able to represent single-case unions as their wrapped type. IMHO this should be the default behavior, but it should be configurable both globally and for specific types.

Pardon if your library already does this - I read through the documentation and couldn't t find any mention of it.

**Comment by vsapronov** [comment]
I agree - single case unions should be represented as wrapped type. Somehow I haven't thought about such scenario and the codebase that I'm working with mostly avoid this pattern.
I can support such behaviour easily, stay tuned...

**Comment by vsapronov** [comment]
Implemented and released in version 0.2.
Here's documentation: https://vsapronov.github.io/FSharp.Json/unions.html#Single-case-union

**Comment by cmeeren** [comment]
That was quick, thanks! 😁
