### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by cmeeren** [vsapronov/FSharp.Json#5]
Tried to install but get the following error:

`Detected package version outside of dependency constraint: FSharp.Json 0.3.0 requires FSharp.Core (>= 4.0.0.1 && < 4.0.1) but version FSharp.Core 4.2.3 was resolved.`

Please support more recent F# versions than 4.0.1. :)

**Comment by vsapronov** [comment]
This is fixed in version 0.3.1 - all versions of FSharp.Core higher then 4.0.0.1 are allowed.
This is the commit: https://github.com/vsapronov/FSharp.Json/commit/bc9a3f03f0591897d2357ab670c8c1d50c614d36
