### ISSUE TITLE
.net core build?

### ISSUE THREAD

**Issue by bohdanszymanik** [vsapronov/FSharp.Json#7]
Would be great rather than have .net core come up with the warning that FSharp.Json was restored using the .NETFramework ...

**Comment by vsapronov** [comment]
Hi Bohdan, I need a bit more context. Could you please describe what exactly does not work for you as expected?

**Comment by bohdanszymanik** [comment]
Oh - it works great! It's just that I tend to run under dotnetcore with the .net tooling and you get the warning that while the project framework is .NETCoreApp, Version=v2.0, FSharp.Json runs under the .NETFramework; the actual warning text follows:

warning NU1701: Package 'FSharp.Json 0.3.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by NullVoxPopuli** [comment]
I'm also getting this warning!
On this project: https://github.com/NullVoxPopuli/CryptoExchangeClient

**Comment by vsapronov** [comment]
Thank you for feedback. I will try to compile for dotnetcore and include into nuget pkg soon.

**Comment by NullVoxPopuli** [comment]
@vsapronov hey, how's it going? do you need help with anything?

**Comment by vsapronov** [comment]
@NullVoxPopuli I don't think I need help with anything particular.
Overall F# related toolset seems to be not ready for dotnet (new structure) projects.
I figured out that easiest way to port library to dotnet core is to have multi-target project in new dotnet core structure. So I already got it compiling for both netcore and netframework. But it looks like Paket and Fake does not work with it nicely yet. So I need to change scripting around packaging and releasing. It will be ready soon...

**Comment by vsapronov** [comment]
@NullVoxPopuli @bohdanszymanik Could you please try version 0.3.3 and let me know here if there are some issues with it on .NET Core. Just have pushed it: https://www.nuget.org/packages/FSharp.Json/0.3.3

**Comment by DieselMeister** [comment]
Hi there. Maybe it is possible to release a netstand2.0 version. Tell me if I am wrong, but this would cover all including .net core 2.0.

**Comment by vladimir-sapronov-zocdoc** [comment]
@DieselMeister FSharp.Json 0.3.3 is built for both .Net Core 2.0 and .Net Framework 4.5.2.
Do you have any practical problem with it as 0.3.3? What is the problem?

The thing is that these multi-target projects are not fun. They are poorly supported in MS products like Visual Studio and F# tools does not make it easier. Paket and Fake are not really supportive. I spent like 3-4 evenings to make it built and published for these two platforms. So I'm not really happy to fight with tooling that Microsoft and F# community never bothered to fix. So I would like to avoid any type of work that would require build/release routine change until absolutely necessary or until MS fixes their crap. So, what is the practical problem?

**Comment by vsapronov** [comment]
@DieselMeister FSharp.Json 0.3.3 is built for both .Net Core 2.0 and .Net Framework 4.5.2.
Do you have any practical problem with it as 0.3.3? What is the problem?

The thing is that these multi-target projects are not fun. They are poorly supported in MS products like Visual Studio and F# tools do not make it easier. Paket and Fake are not really supportive. I spent like 3-4 evenings to make it built and published for these two platforms. So I'm not really happy to fight with tooling that Microsoft and F# community never bothered to fix. So I would like to avoid any type of work that would require build/release routine change until absolutely necessary or until MS fixes their crap. So, what is the practical problem?

**Comment by DieselMeister** [comment]
Hi. I can not use it in .net standard project files. The benefit to use netstandard 2.0 is, that this works also for netcore20.

I tested it and the packaging works fine:

- modify FSharp.Json.fsproj file:
    `<TargetFrameworks>net452;netstandard2.0</TargetFrameworks>`
- run in the solution folder: "dotnet build"
- run in the solution folder: "dotnet pack"

Thats it. Do not use Paket for packaging multiplatform projects.

Found this hint here: [https://github.com/fsprojects/Paket/issues/2330](https://github.com/fsprojects/Paket/issues/2330)

I hope it help, because your Json is excactly what i need.

**Comment by atadi96** [comment]
Hi! What's the status on this? You really just need to add `netstandard2.0` to `TargetFrameworks` and publish the new version as @DieselMeister described it, and it would make a huge difference in consumability. I tried it in a fork and the project builds and all tests pass.

**Comment by vsapronov** [comment]
@atadi96 @DieselMeister @NullVoxPopuli Could you please take a look at release 0.3.4: https://www.nuget.org/packages/FSharp.Json/0.3.4
Now it's built only for Standard.
